services:
  database:
    image: bitnami/postgresql
    env_file: .env
    environment:
      POSTGRESQL_USERNAME: admin
      POSTGRESQL_PASSWORD: 123
      POSTGRESQL_DATABASE: neatcode
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d neatcode"]
      interval: 5s
      timeout: 5s
      retries: 5
